# Generated by Django 5.1.7 on 2025-08-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_userscores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscores',
            options={'managed': True, 'verbose_name': 'User Score', 'verbose_name_plural': 'User Scores'},
        ),
        migrations.AddField(
            model_name='userscores',
            name='attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscores',
            name='failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscores',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscores',
            name='passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='userscores',
            table='',
        ),
    ]
