# Generated by Django 5.1.7 on 2025-08-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_userscores_options_userscores_attempted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscores',
            options={'verbose_name': 'User Score', 'verbose_name_plural': 'User Scores'},
        ),
        migrations.AlterModelTable(
            name='userscores',
            table=None,
        ),
    ]
