# Generated by Django 5.1.7 on 2025-08-16 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_alter_userscores_options_alter_userscores_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscores',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
