# Generated by Django 5.1.7 on 2025-08-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_userscores_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscores',
            name='course',
            field=models.CharField(default='not available', max_length=20),
        ),
    ]
