# Generated by Django 5.1.7 on 2025-06-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload/book_images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
