# Generated by Django 5.1.7 on 2025-07-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0003_alter_book_image_borrowedbook_deletedbook_readbook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='deletedbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='returnedbook',
            name='borrowed_book',
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='DeletedBook',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
        migrations.DeleteModel(
            name='ReturnedBook',
        ),
        migrations.DeleteModel(
            name='ReadBook',
        ),
    ]
