# Generated by Django 5.1.7 on 2025-07-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about_book',
            field=models.TextField(default='About book......'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
