# Generated by Django 5.1.7 on 2025-07-25 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_book_about_book_alter_book_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='borrow_date',
            new_name='borrow_time',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='return_date',
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='return_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
