# Generated by Django 5.1.7 on 2025-07-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_rename_borrow_date_borrowedbook_borrow_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
