# Generated by Django 5.1.7 on 2025-07-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_book_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_quantity',
            field=models.IntegerField(default=models.IntegerField(default=1)),
        ),
    ]
