# Generated by Django 5.2.4 on 2025-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_alter_borrowedbook_book_alter_borrowedbook_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
