# Generated by Django 5.1.7 on 2025-08-13 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_alter_book_available_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='return_time',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='return_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2019, 12, 31)),
            preserve_default=False,
        ),
    ]
