# Generated by Django 5.1.7 on 2025-08-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_rename_return_time_borrowedbook_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
