# Generated by Django 5.1.7 on 2025-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_alter_borrowedbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(blank=True),
        ),
    ]
