# Generated by Django 5.1.7 on 2025-09-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0012_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='fine',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
