# Generated by Django 5.1.7 on 2025-06-30 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatar',
            new_name='passport',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='d_o_b',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('custom', 'Custom')], default='custom', max_length=25),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matric_num',
            field=models.CharField(default=django.utils.timezone.now, max_length=24),
            preserve_default=False,
        ),
    ]
