# Generated by Django 5.1.7 on 2025-06-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_avatar_userprofile_passport_userprofile_d_o_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='matric_num',
        ),
    ]
